# permissions for end users to view remotesubscriptions.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: remotesubscription-viewer-role
rules:
- apiGroups:
  - config.operator.o3
  resources:
  - remotesubscriptions
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - config.operator.o3
  resources:
  - remotesubscriptions/status
  verbs:
  - get
